; --- BOOTSTRAP VECTOR ---
    JMP MAIN
; ------------------------

main:
; --- Start hygiënische macro: INIT (ID: 1) ---
    LDI A, 5
    LDI I, 0
    LDI Y, 100
    LDI X, 0
; --- Einde macro: INIT ---

SPAWN_LOOP:
    TSTE I, Y
    JMPT FLUSH_REMAINING
    CONTEXT A, THREAD_WORKER
    FAIL MATRIX_FULL_HANDLER
    INC I
    JOIN B, SPAWN_LOOP
    ADD X, B
    JMP SPAWN_LOOP

MATRIX_FULL_HANDLER:
    JOIN B, MATRIX_FULL_HANDLER
    ADD X, B
    JMP SPAWN_LOOP

FLUSH_REMAINING:
    JOIN B, ALL_DONE
    ADD X, B
    JMP FLUSH_REMAINING

ALL_DONE:
    SYNC FLUSH_REMAINING
    STO X, 1013
    HALT

THREAD_WORKER:
    LDI M, 42
    LDI L, 42
    MUL M, L
    LDI B, 1
    MUL B, A
    RETURN B